services:
  - type: web
    name: pet-adoption-platform-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: NODE_ENV
        value: production
